Repository fdcl-ftc/fault-tolerant-control, pull requests merged in 2021-05, with the labels that each got.

#38 Add active ftc backstepping
  ftc/agents/backstepping.py
  ftc/models/multicopter.py
  main.py
Labels: documentation, enhancement

#45 Add an active FTC (DSC + CA) module and a script
  ftc/agents/dsc.py
  ftc/models/dryden.py
  ftc/models/multicopter.py
  test/active_ftc.py
Labels: enhancement

#52 Modify dynamics; unit quaternion to DCM
  ftc/models/multicopter.py
Labels: bug

#57 Fix the FDI module
  ftc/agents/fdi.py
  test/active_ftc.py
  test/grouping.py
Labels: bug

#60 Correct multirotor dynamics
  ftc/models/multicopter.py
Labels: bug, documentation

#67 Add direct backstepping controller
  ftc/agents/backstepping.py
  test/backstepping.py
Labels: enhancement
