Repository fdcl-ftc/fault-tolerant-control, pull requests merged in 2021-06, with the labels that each got.

#77 Fix model parameter
  ftc/models/multicopter.py
Labels: bug

#69 Add Scenario A-3
  ftc/agents/CA.py
  ftc/agents/backstepping.py
  ftc/agents/lqr.py
  test/backstepping.py
  test/failure_scenario.py
  test/model_test.py
  test/scenario_a_3.py
Labels: enhancement

#68 Add a scenario A-2 to B-2
  ftc/agents/lqr.py
  ftc/agents/switching.py
  test/scenario_a_2.py
Labels: enhancement

#83 Add calculate_recovery_rate
  ftc/evaluate/evaluate.py
Labels: enhancement

#84 Create modular_test.py (including parallel computation)
  test/modular_test.py
Labels: enhancement

#92 CA.get 의 docstring 추가
  ftc/agents/CA.py
Labels: documentation

#87 Add constrained CA
  ftc/agents/CA.py
  ftc/models/multicopter.py
  test/scenario_a_1.py
Labels: enhancement

#97 Fix a bug that did not work properly when LoE occurs on more than one rotor
  ftc/faults/actuator.py
Labels: bug

#99 Fix CA
  ftc/agents/CA.py
Labels: bug
